//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.MaterialsSuppliers = new HashSet<MaterialsSupplier>();
            this.MaterialsSuppliers1 = new HashSet<MaterialsSupplier>();
        }
    
        public string ClientID { get; set; }
        public string ClientName { get; set; }
        public string ClientAddress { get; set; }
        public string ZipID { get; set; }
        public string OrderID { get; set; }
        public string SalesPersonID { get; set; }
        public string ZipCodeZipID { get; set; }
    
        public virtual ICollection<MaterialsSupplier> MaterialsSuppliers { get; set; }
        public virtual ICollection<MaterialsSupplier> MaterialsSuppliers1 { get; set; }
        public virtual ZipCode ZipCode { get; set; }
    }
}
