//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatu
    {
        public OrderStatu()
        {
            this.PartLocations = new HashSet<PartLocation>();
        }
    
        public string StatusID { get; set; }
        public string StatusName { get; set; }
    
        public virtual ICollection<PartLocation> PartLocations { get; set; }
    }
}
