//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public string OrderID { get; set; }
        public string PartID { get; set; }
        public string StatusID { get; set; }
        public string Quanity { get; set; }
        public string ClientID { get; set; }
        public string MaterialsSupplierSupplierID { get; set; }
    
        public virtual MaterialsSupplier MaterialsSupplier { get; set; }
    }
}
