//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part
    {
        public Part()
        {
            this.PartsMaterials = new HashSet<PartsMaterial>();
        }
    
        public string PartsID { get; set; }
        public string PartName { get; set; }
        public string LoctionID { get; set; }
        public string SupplierID { get; set; }
        public string MaterialID { get; set; }
        public string PartLocationLocationID { get; set; }
    
        public virtual ICollection<PartsMaterial> PartsMaterials { get; set; }
        public virtual PartLocation PartLocation { get; set; }
    }
}
