//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartLocation
    {
        public PartLocation()
        {
            this.Parts = new HashSet<Part>();
        }
    
        public string LocationID { get; set; }
        public string LocationName { get; set; }
        public string OrderStatuStatusID { get; set; }
    
        public virtual OrderStatu OrderStatu { get; set; }
        public virtual ICollection<Part> Parts { get; set; }
    }
}
