//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZipCode
    {
        public ZipCode()
        {
            this.Clients = new HashSet<Client>();
        }
    
        public string ZipID { get; set; }
        public string State { get; set; }
        public string City { get; set; }
    
        public virtual ICollection<Client> Clients { get; set; }
    }
}
